model_id: sam_eq
image_emb_variant: sam_withcontext_equal
text_emb_variant: vild_text_embeddings_80
ckpt_dir: weights/sam_eq
log_csv:  weights/sam_eq/loss.csv

roi_dim: 256
hidden_dim: 512
embed_dim: 1024
num_classes: 80
temperature: 0.01
lambda_distill: 45

optimizer: adamw
lr: 1.0e-4
weight_decay: 1.0e-4
batch_size: 4
epochs: 10
warmup_steps: 500
scheduler: cosine
amp: fp16
seed: 42
